!    ' |\r|\n|\t'

    "IF"
    "ELSE"
    "WHILE"
    "DO"
    "FUNCTION"
    "USE"
    "RETURN"
    "TRUE"
    "FALSE"
    'X'
    'Y'
    '<<'
    '>>'
    '\['
    '\]'
    '{'
    '}'
    ';'
    '='
    '=='
    '!='
    '<='
    '>='
    '>'
    '<'
    '\+'
    '\-'
    '/'
    '\*'
    ','
    '\('
    '\)'
    '#'
    '\:'
    '\|'
    '\.'
    '[A-Za-z_][A-Za-z0-9_]*'           Identifier
    '\'([^\']|\'\')*\''                String                                [* %match = %match.substr( 1, %match.length - 2 );
                                                                                %match = %match.replace( /''/g, "\'" );    *]
    '[0-9]+'                           Integer
    '[0-9]+\.[0-9]*|[0-9]*\.[0-9]+'    Float
    ;

##

Program:  Program Stmt                                                       [* this.execute( %2 ); *]
        |
        ;

Stmt_List:     Stmt_List Stmt                                                [* %% = this.createNode('node_op', 'op_none', %1, %2 ); *]
        |
        ;

Param_List:    Param_List ',' Expression                                     [* %% = this.createNode('node_op', 'op_paramlst', %1, %3 ); *]
        | Expression                                                         [* %% = this.createNode('node_op', 'op_param', %1); *]
        ;

Prop_List:     Prop_List ',' Prop                                            [* %% = this.createNode('node_op', 'op_proplst', %1, %3 ); *]
        | Prop
        |
        ;

Prop:          Identifier ':' Expression                                     [* %% = this.createNode('node_op', 'op_prop', %1, %3 ); *]
        ;
                                
Param_Def_List:Param_Def_List ',' Identifier                                 [* %% = this.createNode('node_op', 'op_paramdeflst', %1, %3 ); *]
        | Identifier                                                         [* %% = this.createNode('node_op', 'op_paramdef', %1); *]
        |
        ;

Stmt:          IF Expression Stmt                                            [* %% = this.createNode('node_op', 'op_if', %2, %3 ); *]
        | IF Expression Stmt ELSE Stmt                                       [* %% = this.createNode('node_op', 'op_if_else', %2, %3, %5 ); *]
        | WHILE Expression Stmt                                              [* %% = this.createNode('node_op', 'op_while', %2, %4 ); *]
        | DO Stmt WHILE Expression ';'                                       [* %% = this.createNode('node_op', 'op_for', %2, %4 ); *]
        | USE Identifier ';'                                                 [* %% = this.createNode('node_op', 'op_use', %2 ); *]
        | RETURN Stmt                                                        [* %% = this.createNode('node_op', 'op_return', %2 ); *]
        | Identifier '=' Expression ';'                                      [* %% = this.createNode('node_op', 'op_assign', %1, %3 ); *]
        | Identifier '.' Identifier '=' Expression ';'                       [* %% = this.createNode('node_op', 'op_property', %1, %3, %5 ); *]
        | '.' Identifier '=' Expression ';'                                  [* %% = this.createNode('node_op', 'op_propnoob', %2, %4 ); *]
        | Expression ';'                                                     [* %% = this.createNode('node_op', 'op_noassign', %1 ); *]
        | '{' Stmt_List '}'                                                  [* %% = %2; *]
        | ';'                                                                [* %% = this.createNode('node_op', 'op_none' ); *]
        ;
                
Expression:    Expression '==' AddSubExp                                     [* %% = this.createNode('node_op', 'op_equ', %1, %3 ); *]
        | Expression '<' AddSubExp                                           [* %% = this.createNode('node_op', 'op_lot', %1, %3 ); *]
        | Expression '>' AddSubExp                                           [* %% = this.createNode('node_op', 'op_grt', %1, %3 ); *]
        | Expression '<=' AddSubExp                                          [* %% = this.createNode('node_op', 'op_loe', %1, %3 ); *]
        | Expression '>=' AddSubExp                                          [* %% = this.createNode('node_op', 'op_gre', %1, %3 ); *]
        | Expression '!=' AddSubExp                                          [* %% = this.createNode('node_op', 'op_neq', %1, %3 ); *]
        | AddSubExp
        ;

AddSubExp:    AddSubExp '-' MulDivExp                                        [* %% = this.createNode('node_op', 'op_sub', %1, %3 ); *]
        | AddSubExp '+' MulDivExp                                            [* %% = this.createNode('node_op', 'op_add', %1, %3 ); *]
        | MulDivExp
        ;
                
MulDivExp:    MulDivExp '*' NegExp                                           [* %% = this.createNode('node_op', 'op_mul', %1, %3 ); *]
        | MulDivExp '/' NegExp                                               [* %% = this.createNode('node_op', 'op_div', %1, %3 ); *]
        | NegExp
        ;
                
NegExp:        '-' ExtValue                                                  [* %% = this.createNode('node_op', 'op_neg', %2 ); *]
        | ExtValue
        ;

ExtValue:      ExtValue '[' AddSubExp ']'                                    [* %% = this.createNode('node_op', 'op_extvalue', %1, %3); *]
        | Value
        ;

Value:        Integer                                                        [* %% = this.createNode('node_const', %1 ); *]
        | Float                                                              [* %% = this.createNode('node_const', %1 ); *]
        | Identifier                                                         [* %% = this.createNode('node_var', %1 ); *]
        | '(' Expression ')'                                                 [* %% = %2; *]
        | String                                                             [* %% = this.createNode('node_str', %1); *]
        | Identifier '(' Param_List ')'                                      [* %% = this.createNode('node_op', 'op_execfun', %1, %3); *]
        | Identifier '(' Param_List ')' '<<' Prop_List '>>'                  [* %% = this.createNode('node_op', 'op_execfun', %1, %3, %6); *]
        | FUNCTION '(' Param_Def_List ')' '{' Stmt_List '}'                  [* %% = this.createNode('node_op', 'op_function', %3, %6); *]
        | X '(' Identifier ')'                                               [* %% = this.createNode('node_method', 'x', %3); *]
        | Y '(' Identifier ')'                                               [* %% = this.createNode('node_method', 'y', %3); *]
        | Identifier '.' Identifier                                          [* %% = this.createNode('node_property', %1, %3); *]
        | '<<' Prop_List '>>'                                                [* %% = this.createNode('node_op', 'op_proplst_val', %2); *]
        | '[' Param_List ']'                                                 [* %% = this.createNode('node_op', 'op_array', %2); *]
        | TRUE                                                               [* %% = this.createNode('node_const_bool', %1 ); *]
        | FALSE                                                              [* %% = this.createNode('node_const_bool', %1 ); *]
        ;

